Maximum_of_each_sequence : Maximum_of_each_sequence.o
	g++ -o Maximum_of_each_sequence Maximum_of_each_sequence.o
Maximum_of_each_sequence.o : Maximum_of_each_sequence.cc
	g++ -c Maximum_of_each_sequence.cc
.PHONY:

clean:
	rm Maximum_of_each_sequence
	rm Maximum_of_each_sequence.o