Harmonicnumbers : Harmonicnumbers.o
	g++ -o Harmonicnumbers Harmonicnumbers.o
Harmonicnumbers.o : Harmonicnumbers.cc
	g++ -c Harmonicnumbers.cc
.PHONY:

clean:
	rm Harmonicnumbers
	rm Harmonicnumbers.o