vowels_and_consonants : vowels_and_consonants.o
	g++ -o vowels_and_consonants vowels_and_consonants.o
vowels_and_consonants.o : vowels_and_consonants.cc
	g++ -c vowels_and_consonants.cc
.PHONY:

clean:
	rm vowels_and_consonants
	rm vowels_and_consonants.o