First_position_of_ever : First_position_of_ever.o
	g++ -o First_position_of_ever First_position_of_ever.o
First_position_of_ever.o : First_position_of_ever.cc
	g++ -c First_position_of_ever.cc
.PHONY:

clean:
	rm First_position_of_ever
	rm First_position_of_ever.o