Looking_for_an_a : Looking_for_an_a.o
	g++ -o Looking_for_an_a Looking_for_an_a.o
Looking_for_an_a.o : Looking_for_an_a.cc
	g++ -c Looking_for_an_a.cc
.PHONY:

clean:
	rm Looking_for_an_a
	rm Looking_for_an_a.o