Counting_frequences : Counting_frequences.o
	g++ -o Counting_frequences Counting_frequences.o
Counting_frequences.o : Counting_frequences.cc
	g++ -c Counting_frequences.cc
.PHONY:

clean:
	rm Counting_frequences
	rm Counting_frequences.o