Harmonicnumbers2 : Harmonicnumbers2.o
	g++ -o Harmonicnumbers2 Harmonicnumbers2.o
Harmonicnumbers2.o : Harmonicnumbers2.cc
	g++ -c Harmonicnumbers2.cc
.PHONY:

clean:
	rm Harmonicnumbers2
	rm Harmonicnumbers2.o