Sum_of_fractions : Sum_of_fractions.o
	g++ -o Sum_of_fractions Sum_of_fractions.o
Sum_of_fractions.o : Sum_of_fractions.cc
	g++ -c Sum_of_fractions.cc
.PHONY:

clean:
	rm Sum_of_fractions
	rm Sum_of_fractions.o