Statistical_measures : Statistical_measures.o
	g++ -o Statistical_measures Statistical_measures.o
Statistical_measures.o : Statistical_measures.cc
	g++ -c Statistical_measures.cc
.PHONY:

clean:
	rm Statistical_measures
	rm Statistical_measures.o