Equal_to_the_last_one : Equal_to_the_last_one.o
	g++ -o Equal_to_the_last_one Equal_to_the_last_one.o
Equal_to_the_last_one.o : Equal_to_the_last_one.cc
	g++ -c Equal_to_the_last_one.cc
.PHONY:

clean:
	rm Equal_to_the_last_one
	rm Equal_to_the_last_one.o