suma_de_digitos : suma_de_digitos.o
	g++ -o suma_de_digitos suma_de_digitos.o
suma_de_digitos.o : suma_de_digitos.cc
	g++ -c suma_de_digitos.cc
.PHONY:

clean:
	rm suma_de_digitos
	rm suma_de_digitos.o