longest_shortest : longest_shortest.o
	g++ -o longest_shortest longest_shortest.o
longest_shortest.o : longest_shortest.cc
	g++ -c longest_shortest.cc
.PHONY:

clean:
	rm longest_shortest
	rm longest_shortest.o