cuadrado_asteriscos : cuadrado_asteriscos.o
	g++ -o cuadrado_asteriscos cuadrado_asteriscos.o
cuadrado_asteriscos.o : cuadrado_asteriscos.cc
	g++ -c cuadrado_asteriscos.cc
.PHONY:

clean:
	rm cuadrado_asteriscos
	rm cuadrado_asteriscos.o