time_descomposition : time_descomposition.o
	g++ -o time_descomposition time_descomposition.o
time_descomposition.o : time_descomposition.cc
	g++ -c time_descomposition.cc
.PHONY:

clean:
	rm time_descomposition
	rm time_descomposition.o