Divisors_in_order : Divisors_in_order.o
	g++ -o Divisors_in_order Divisors_in_order.o
Divisors_in_order.o : Divisors_in_order.cc
	g++ -c Divisors_in_order.cc
.PHONY:

clean:
	rm Divisors_in_order
	rm Divisors_in_order.o