Sequentials_search_in_an_array : Sequentials_search_in_an_array.o
	g++ -o Sequentials_search_in_an_array Sequentials_search_in_an_array.o
Sequentials_search_in_an_array.o : Sequentials_search_in_an_array.cc
	g++ -c Sequentials_search_in_an_array.cc
.PHONY:

clean:
	rm Sequentials_search_in_an_array
	rm Sequentials_search_in_an_array.o