Increasing_pairs : Increasing_pairs.o
	g++ -o Increasing_pairs Increasing_pairs.o
Increasing_pairs.o : Increasing_pairs.cc
	g++ -c Increasing_pairs.cc
.PHONY:

clean:
	rm Increasing_pairs
	rm Increasing_pairs.o