delete_blank_lines : delete_blank_lines.o
	g++ -o delete_blank_lines delete_blank_lines.o
delete_blank_lines.o : delete_blank_lines.cc
	g++ -c delete_blank_lines.cc
.PHONY:

clean:
	rm delete_blank_lines
	rm delete_blank_lines.o