Balanced_numbers : Balanced_numbers.o
	g++ -o Balanced_numbers Balanced_numbers.o
Balanced_numbers.o : Balanced_numbers.cc
	g++ -c Balanced_numbers.cc
.PHONY:

clean:
	rm Balanced_numbers
	rm Balanced_numbers.o